"""
backend/db/models.py
---------------------
SQLAlchemy ORM models for persistent storage.
Tables: WorkOrder, HITLEvent, AuditLog
"""

from __future__ import annotations

import json
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class WorkOrder(Base):
    """Persisted work order generated by the agentic pipeline."""

    __tablename__ = "work_orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    asset_id: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    failure_mode: Mapped[str] = mapped_column(String(256), nullable=False)
    recommended_action: Mapped[str] = mapped_column(Text, nullable=False)
    rul_estimate: Mapped[float | None] = mapped_column(Float, nullable=True)
    anomaly_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    diagnosis_confidence: Mapped[float] = mapped_column(Float, default=0.0)

    # JSON-serialised lists stored as text
    _shap_top_features: Mapped[str] = mapped_column(
        "shap_top_features", Text, default="[]"
    )
    _parts: Mapped[str] = mapped_column("parts", Text, default="[]")
    _manual_refs: Mapped[str] = mapped_column("manual_refs", Text, default="[]")

    rag_context: Mapped[str | None] = mapped_column(Text, nullable=True)
    priority: Mapped[str] = mapped_column(String(16), default="medium")
    estimated_duration_hrs: Mapped[float] = mapped_column(Float, default=1.0)
    auto_generated: Mapped[bool] = mapped_column(Boolean, default=True)

    # HITL state
    status: Mapped[str] = mapped_column(
        String(32), default="pending_approval", index=True
    )
    rejection_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    proposed_start: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    technician_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    hitl_events: Mapped[list["HITLEvent"]] = relationship(
        "HITLEvent", back_populates="work_order", cascade="all, delete-orphan"
    )

    # Python-level list accessors
    @property
    def shap_top_features(self) -> list[str]:
        return json.loads(self._shap_top_features or "[]")

    @shap_top_features.setter
    def shap_top_features(self, value: list[str]) -> None:
        self._shap_top_features = json.dumps(value)

    @property
    def parts(self) -> list[str]:
        return json.loads(self._parts or "[]")

    @parts.setter
    def parts(self, value: list[str]) -> None:
        self._parts = json.dumps(value)

    @property
    def manual_refs(self) -> list[str]:
        return json.loads(self._manual_refs or "[]")

    @manual_refs.setter
    def manual_refs(self, value: list[str]) -> None:
        self._manual_refs = json.dumps(value)


class HITLEvent(Base):
    """Audit log for each human approve/reject action on a work order."""

    __tablename__ = "hitl_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    work_order_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("work_orders.id"), nullable=False, index=True
    )
    action: Mapped[str] = mapped_column(String(16), nullable=False)   # approve | reject
    technician_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    work_order: Mapped[WorkOrder] = relationship("WorkOrder", back_populates="hitl_events")


class AuditLog(Base):
    """Append-only log for every significant system event."""

    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    event_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    asset_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    correlation_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
