// frontend/app/workorders/page.tsx
"use client";

import React from "react";
import { useWorkOrders } from "@/hooks/useFleetData";
import { WorkOrderTable } from "@/components/organisms/WorkOrderTable";
import { MetricCard } from "@/components/molecules/MetricCard";
import { Spinner } from "@/components/atoms/Spinner";
import { ClipboardList, AlertCircle, CheckCircle2, XCircle } from "lucide-react";

export default function WorkOrdersPage() {
  const { data, isLoading } = useWorkOrders();

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] gap-3">
        <Spinner size="lg" />
        <span className="text-sm text-text-muted">Retrieving maintenance directory...</span>
      </div>
    );
  }

  const items = data?.items ?? [];
  const pendingCount = data?.pending ?? 0;
  const approvedCount = data?.approved ?? 0;
  const rejectedCount = data?.rejected ?? 0;

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Page Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-text-primary">
          Work Order Console
        </h1>
        <p className="text-sm text-text-muted mt-1">
          Review, approve, and assign maintenance schedules generated by the diagnostic agent.
        </p>
      </div>

      {/* Summary Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <MetricCard
          title="Total Requests"
          value={items.length}
          icon={<ClipboardList className="h-5 w-5 text-accent-blue" />}
          description="In directory"
        />
        <MetricCard
          title="Pending Approval"
          value={pendingCount}
          icon={<AlertCircle className="h-5 w-5 text-accent-amber" />}
          description="Awaiting HITL action"
          glow={pendingCount > 0 ? "amber" : "none"}
        />
        <MetricCard
          title="Active Schedules"
          value={approvedCount}
          icon={<CheckCircle2 className="h-5 w-5 text-accent-teal" />}
          description="Technician dispatched"
        />
        <MetricCard
          title="Rejected Logs"
          value={rejectedCount}
          icon={<XCircle className="h-5 w-5 text-accent-red" />}
          description="De-escalated cases"
        />
      </div>

      {/* Work Orders Table */}
      <div className="space-y-4">
        <h3 className="text-lg font-semibold tracking-tight text-text-primary">
          Maintenance Records Registry
        </h3>
        <WorkOrderTable workOrders={items} />
      </div>
    </div>
  );
}
